development:
  adapter: postgresql
  encoding: utf8
  database: one_page_list_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: one_page_list_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: one_page_list
  pool: 5